spring.application.name=trabalhoFinal
# Define qual perfil será usado (mude para prod quando for subir no servidor)
spring.profiles.active=dev

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USUARIO_EMAIL}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

