spring.application.name=trabalhoFinal

spring.datasource.url=jdbc:h2:file:./data/mecanica
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=123456

# Adicione estes valores diretamente aqui para resolver o erro:
USUARIO_EMAIL=seu-email-aqui@gmail.com
EMAIL_PASS=sua-senha-de-app-aqui

# Certifique-se de que as configurações de e-mail também estão aqui:
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USUARIO_EMAIL}
spring.mail.password=${EMAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true